### ISSUE TITLE
Code-style consistency

### ISSUE THREAD

**Issue by KhashayarMirMS** [ShahriarHD/patterns-blue#3]
There are a lot of inconsistent uses of semicolons, double-quotes vs single-quotes, and general problems with unused variables and imports.
We could use more specific eslint configs and pre-commit hooks to ensure the codes remain clean.

**Comment by KhashayarMirMS** [comment]
I provided [this pull request](https://github.com/ShahriarHD/patterns-blue/pull/4) to address these issues.

**Comment by ShahriarHD** [comment]
Thanks @KhashayarMirMS for this! Certainly made the codebase much more beautiful <3
